Add version of CI with renv override

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -124,6 +124,97 @@ jobs:
         with:
           name: results-${{ steps.slugify.outputs.slug }}
           path: results.tar.gz
+  
+  norenv:
+    runs-on: ubuntu-24.04
+    strategy:
+      fail-fast: false
+      matrix:
+        target:
+          - R/running.R
+          - R/app.R
+          - R/app.R --metadata_json url('https://osf.io/hgacq/download') --phylogeny_json url('https://osf.io/6j4rg/download') --only_thru_mlsclust TRUE
+          - R/app.R --metadata_json url('https://osf.io/hgacq/download') --phylogeny_json url('https://osf.io/6j4rg/download') --only_thru_thresholds TRUE
+          - R/app.R --metadata_json url('https://osf.io/hgacq/download') --phylogeny_json url('https://osf.io/6j4rg/download') --only_thru_stats TRUE
+          - R/app.R --max_date as.Date('2020-10-15')
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
+        with:
+          token: '${{ secrets.GITHUB_TOKEN }}'
+
+      - name: Install system dependencies
+        run: |
+          sudo apt-get update
+          # Install required system libraries
+          sudo apt-get install -y \
+            build-essential \
+            cmake \
+            curl \
+            libblas-dev \
+            libbz2-dev \
+            libcurl4-openssl-dev \
+            libfontconfig1-dev \
+            libfreetype6-dev \
+            libgit2-dev \
+            libharfbuzz-dev \
+            libicu-dev \
+            liblapack-dev \
+            liblzma-dev \
+            libfribidi-dev \
+            libjpeg-dev \
+            libpng-dev \
+            libssl-dev \
+            libtiff5-dev \
+            libxml2-dev \
+            zlib1g-dev
+
+      - name: Set up R 3.6.3
+        uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: '3.6.3'
+
+      # https://github.com/actions/cache/blob/5a3ec84eff668545956fd18022155c47e93e2684/examples.md#r---renv
+      - name: Get R and OS version
+        id: get-version
+        run: |
+          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
+          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
+        shell: Rscript {0}
+
+      - name: Install R dependencies
+        env:
+          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          ./install_packages.sh
+
+      - name: Run R script
+        run: |
+          timeout 30m Rscript ${{ matrix.target }} \
+            || ( [[ $? -eq 124 ]] && \
+            echo "timing out to prevent job kill due to resource use" )
+
+      - name: Consolidate output to results/
+        run: |
+          mkdir -p results
+          mv Rplots.pdf results/ || echo "Rplots.pdf not found"
+          mv stat_results results/ || echo "stat_results not found"
+          tar -czvf results.tar.gz results/
+
+      - name: Slugify matrix.target
+        id: slugify
+        run: |
+          RAW_TARGET="${{ matrix.target }}"
+          SLUG=$(echo "$RAW_TARGET" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
+          echo "slug=$SLUG" >> $GITHUB_OUTPUT
+
+      - name: Upload results artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: results-${{ steps.slugify.outputs.slug }}
+          path: results.tar.gz
 
   deploy-ghcr:
     name: Docker Image Deploy
